{
	"description": "Test #set parser to produce error output (#870, en, verify that #set calls do not affect each other with previous errors)",
	"properties": [
		{
			"name": "Has number",
			"contents": "[[Has type::Number]]"
		}
	],
	"subjects": [
		{
			"name": "Set-number-with-error",
			"contents": "{{#set:Has number=12}} {{#set:Has number=32a}} {{#set:Has number=66}} {{#set:Has number=88b}}"
		}
	],
	"parser-testcases": [
		{
			"about": "#0 with error",
			"subject": "Set-number-with-error",
			"store": {
				"semantic-data": {
					"strict-mode-valuematch": false,
					"propertyCount": 4,
					"propertyKeys": [ "Has_number", "_ERRC", "_SKEY", "_MDAT" ],
					"propertyValues": [ 12, 66 ]
				}
			},
			"expected-output": {
				"to-contain": [
					"&quot;a&quot; can not be assigned to a declared number type with value 32.",
					"&quot;b&quot; can not be assigned to a declared number type with value 88."
				]
			}
		}
	],
	"settings": {
		"wgContLang": "en",
		"smwgPageSpecialProperties": [ "_MDAT" ]
	},
	"meta": {
		"version": "0.1",
		"is-incomplete": false,
		"debug": false
	}
}